version: "3.0"

services:
  mysqldb:
    image: mysql:latest
    volumes:
      - "mysql_data:/peopleflow"
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: peopleflow

volumes:
  mysql_data:
    driver: local